name: Send Notification

on:
  repository_dispatch:
    types: [notify]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Send Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ github.event.client_payload.chat_id }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ github.event.client_payload.message }}
          document: ${{ github.event.client_payload.file }}

      - if: github.event.client_payload.file != ''
        name: Delete file using GitHub API
        run: |
          curl -L \
          -X DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/theplayernumber1/notify/contents/${{ github.event.client_payload.file }} \
          -d '{
            "message": "Delete sent file",
            "committer": {
              "name": "theplayernumber1",
              "email": "your-email@example.com"
            },
            "sha": "$(curl -s -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" -H "User-Agent: theplayernumber1" https://api.github.com/repos/theplayernumber1/notify/contents/${{ github.event.client_payload.file }} | jq -r '.sha')"
          }'
