name: Send Notification

on:
  repository_dispatch:
    types: [notify]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Send Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ github.event.client_payload.chat_id }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ github.event.client_payload.message }}
          document: ${{ github.event.client_payload.file }}

      - if: github.event.client_payload.file != ''
        name: Delete file using GitHub API
        run: |
          curl -X DELETE \
          -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -H "User-Agent: ${{ github.actor }}" \
          https://api.github.com/repos/${{ github.repository }}/contents/${{ github.event.client_payload.file }} \
          -d '{
            "message": "Delete sent file",
            "sha": "$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" -H "User-Agent: ${{ github.actor }}" https://api.github.com/repos/${{ github.repository }}/contents/${{ github.event.client_payload.file }} | jq -r '.sha')",
            "committer": {
              "name": "${{ github.actor }}",
              "email": "your-email@example.com"
            },
            "author": {
              "name": "${{ github.actor }}",
              "email": "your-email@example.com"
            }
          }'
