name: Send Notification

on:
  repository_dispatch:
    types: [notify]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Send Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ github.event.client_payload.chat_id }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ github.event.client_payload.message }}
          document: ${{ github.event.client_payload.file }}

      - name: Delete file after sending
        if: github.event.client_payload.file != ''
        run: |
          API_URL="https://api.github.com/repos/theplayernumber1/notify/contents/${{ github.event.client_payload.file }}"
          HEADERS="-H 'Accept: application/vnd.github+json' -H 'Authorization: Bearer ${{ secrets.GH_TOKEN }}' -H 'User-Agent: Notify Action v1.2.1' -H 'X-GitHub-Api-Version: 2022-11-28'"
          SHA=$(curl -s $HEADERS $API_URL | jq -r '.sha')
          curl -L -X DELETE $HEADERS $API_URL -d @- <<EOF
          {
            "message": "Deleted sent file",
            "committer": {
              "name": "theplayernumber1",
              "email": "dev@amanstark.com"
            },
            "sha": "$SHA"
          }
          EOF
